### PR TITLE
865 - Clean up test_load_data

### PR DESCRIPTION
**Pull request by avrohomgottlieb**
## Issue Number

Closes https://github.com/AlexsLemonade/scpca-portal/issues/865

## Purpose/Implementation Notes

In light of the addition of the new `test_loader` module, which handles integration testing throughout the project_creation and computed_file_generation workflows, `test_load_data` was refactored to focus exclusively on verifying command line inputs. 

This module includes a series of unit tests which mock the actual `loader` methods called under the hood and make sure that function inputs are correctly passed.

## Types of changes

- Refactor (addresses code organization and design mentioned in corresponding issue)
- New feature (non-breaking change which adds functionality)

## Functional tests

Testing module

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

## Screenshots

N/A

### CODE REVIEW

**Comment by avrohomgottlieb** [comment]
@davidsmejia I have yet to include refactored tests for  `test_metadata` in this PR. I wanted to clarify with you the two approaches that I was thinking could be taken with `test_metadata`:
- Do we want to implement similar tests over there? 
- Does the fact that all relevant tests for `test_metadata` will be covered in `test_load_data` mean that `test_metadata` is no longer necessary?

**Comment by davidsmejia** [comment]
> @davidsmejia I have yet to include refactored tests for `test_metadata` in this PR. I wanted to clarify with you the two approaches that I was thinking could be taken with `test_metadata`:
> 
>     * Do we want to implement similar tests over there?

Yes, we need coverage to ensure that `test_metadata` is written correctly and should have the same checks to ensure that expected behavior is supported.

>     * Does the fact that all relevant tests for `test_metadata` will be covered in `test_load_data` mean that `test_metadata` is no longer necessary?

No, while it is a similar implementation, it is still a different file which could contain it's own errors. So we should still check for that.

**Review by davidsmejia — APPROVED** [review]
LGTM

**Review by davidsmejia — COMMENTED** [review]
LGTM

**Pull request merged**
