### PR TITLE
598 - Fix the delay in updating DownloadOptionsContext state to resolve a bug

### PR DESCRIPTION
**Pull request by nozomione**
## Issue Number
Closing #598

## Purpose/Implementation Notes
I've fixes the state errors for the samples table's download options modal.

Please see the implementation details listed in the "solution or next step" section in the issue. ~~Additionally, I've added the `useUpdateFormatOptions` hook (f111423d375dbfd05423b01b9283ff1184670716) for DRY~~ (**Updated:** removed at 91da3df85c17fc2b84272ee4de3cab9edd8a0201).

Please see the latest UI [here](https://scpca-portal-iycf8dzac-ccdl.vercel.app/projects/SCPCP000006).  

## Types of changes
- Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nozomione** [comment]
This fix should be included before deploying the official AnnData (removing the AnnData loading banner) to `prod`. 

However, PRs labeled 'low' for `[AnnData Code Review]` do not need to be reviewed before deployment (I've added the note to them). Thank you, @davidsmejia!

**Comment by davidsmejia** [comment]
This looks good but I think it makes more sense to keep the new hook's logic as an exposed function that can be consumed directly by the `useDownloadOptionsContext` and then made public and can be used by the components the consume that hook.

So I'd like to see that brought back into the `useDownloadOptionsContext` and then this will look good to me

**Comment by nozomione** [comment]
> This looks good but I think it makes more sense to keep the new hook's logic as an exposed function that can be consumed directly by the `useDownloadOptionsContext` and then made public and can be used by the components the consume that hook.
> 
> So I'd like to see that brought back into the `useDownloadOptionsContext` and then this will look good to me

In `useDownloadOptionsContext`, I've removed `useUpdateFormatOptions` and replaced with the original implementation (0e60d0e85dbac5147f868c8bf7daf909e86bf281). 

Additionally, I've adjusted `DownloadOptionsModal` to use helpers directly with `useEffect` to handle the update of local data format options (5205d39e3bec449ba6c355d6bffc679ca5a5e570). 

This PR is ready for another look, thank you @davidsmejia !

**Review by davidsmejia — APPROVED** [review]
LGTM

**Pull request merged**
