### PR TITLE
575 - Re-open call for contributions: Update contribution guidelines, add PDF, and remove card

### PR DESCRIPTION
**Pull request by nozomione**
## Issue Number

Closing #575

## Purpose/Implementation Notes
I've updated the following: 
- Added the call for contribution banner except for the following pages (matches the previous implementation):
  - `/contribute`
  - `/privacy-policy`
  - `/terms-of-use` 
- Updated the `hs_form` link to a new link in `config/index`
- Added the PDF `contributing-guidelines.pdf` to the `/public` folder 
- Created the `ContributePhaseOutBanner` component for future use (e.g., [#430](https://github.com/AlexsLemonade/scpca-portal/issues/430)) at 7e8b536f3ab5afddbe58c03a5698d7e2d1be836d

On the `/contribute` page:
- Removed the phase out contribution banner
- Added the guidelines PDF download button

Please see the latest UI [here](https://scpca-portal-pe89d4euy-ccdl.vercel.app/).

I am tagging @dvenprasad for the UI review in case, thank you!

## Types of changes
What types of changes does your code introduce?
- New feature (non-breaking change which adds functionality)

## Functional tests

List out the functional tests you've completed to verify your changes work locally.

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

Please attach any screenshots that illustrate these changes.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Looks good from my perspective

**Review by davidsmejia — APPROVED** [review]
LGTM. Let's hold off on merging this to dev as there are other things that need to be deployed first.

**Comment by davidsmejia** [comment]
1. The issue that you can see is that ccomputedFile is not defined and that it is in `DownloadStarted` component. That's in the error description. So if you look for that in the file you can see it isn't there.
2. This is Sentry trying to be helpful. This error occurred on the localhost domain 2 weeks ago.

**Comment by nozomione** [comment]
> 1. The issue that you can see is that ccomputedFile is not defined and that it is in `DownloadStarted` component. That's in the error description. So if you look for that in the file you can see it isn't there.
> 
>     2. This is Sentry trying to be helpful. This error occurred on the localhost domain 2 weeks ago.

Yes, I was thinking we didn't edit the `DownloadStarted` in this PR and it must be an old reference error! Thank you for the note David!

**Pull request merged**
