### PR TITLE
530 - About Page Updates - Features and Enhancements + Support the Data Lab

### PR DESCRIPTION
**Pull request by nozomione**
## Issue Number

Closing #530

## Purpose/Implementation Notes

Updated the Features and Enhancements and Support the Data Lab sections in the about page with the new design ([figma](https://www.figma.com/file/EVZeubNFGSgfRQFr1yGXhs/scpca-about-page-redo?type=whiteboard&node-id=20%3A1326&t=EEb4sdKlUX77iZ6m-1)). 

Please see the latest UI [here](https://scpca-portal-4ri6t9tfm-ccdl.vercel.app/about).

## Types of changes
- New feature (non-breaking change which adds functionality)

## Functional tests

List out the functional tests you've completed to verify your changes work locally.

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by dvenprasad — COMMENTED** [review]
This seems more obvious in this PR but the `Building the portal` section seems off centre with the `features and enhancements` section

Screenshot 2024-01-31 at 11 57 55

Maybe we could move the figure a little to the right?

**Comment by nozomione** [comment]
> move the figure a little to the right?

Opps 😅, adjusted!

**Review by dvenprasad — APPROVED** [review]
Looking good! 
There's one suggested change to remove a full stop from a link.

🦎 🦎 🦎

**Comment by nozomione** [comment]
> There's one suggested change to remove a full stop from a link.

Yes, it's done at 32cfde0d015dd358488f7ab08774812537eb0196 👍 !

**Comment by nozomione** [comment]
@davidsmejia Fyi, I made a minor clean up at b61c1fdc040b0a3acf5cb37cd80de689f18f6515, thank you!

**Review by davidsmejia — APPROVED** [review]
LGTM

**Pull request merged**
